project_id = "iqsrwygslsjowvndmbsj"

[auth]
enabled = true
site_url = "https://0a6f24f0-4662-4eec-8e52-414c58a74125.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[functions.create-admin-user]
verify_jwt = false

[functions.create-user-with-role]
verify_jwt = false

[functions.generate-qr-codes]
verify_jwt = false

[functions.export-qr-codes]
verify_jwt = false