// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqsrwygslsjowvndmbsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxc3J3eWdzbHNqb3d2bmRtYnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTEyNDMsImV4cCI6MjA2OTQ2NzI0M30.VXxOiPoz574ZDjxUBImiHKMrjtu2Ms-GINLV9UaIneA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});